describe('Banking framework testing', function() {
	
	beforeEach(function() {
		browser.get('http://www.way2automation.com/angularjs-protractor/banking/#/login');
    browser.manage().window().maximize();
	});
	
	afterEach(function() {
		console.log("test case successful");
	});
	
  xit('login page', function() {
   	
    expect(element(by.partialButtonText('Customer Login')));
    expect(element(by.partialButtonText('Bank Manager Login')));
 
	console.log('Customer login and manager login present on page');

   });
  xit('Manager Login', function() {
	   
	   element(by.partialButtonText('Bank Manager Login')).click();
	    
	    var center=element.all(by.className('center')).getText();
	    //console.log(center);
	    
	    expect(element(by.partialButtonText('Add Customer')));
	    expect(element(by.partialButtonText('Open Account')));
	    expect(element(by.partialButtonText('Customers')));
	 
		console.log('Manager page lunched with the Add customer,Open accounts,Customer');
	   });
  
  xit('Add Customers', function() {
	   		
	    element(by.partialButtonText('Bank Manager Login')).click();
	    element(by.buttonText('Add Customer')).click();

	   element(by.model('fName')).sendKeys('Shubhangi');
	   element(by.model('lName')).sendKeys('Bhosale');
	   element(by.model('postCd')).sendKeys('94026');
	   
	  element(by.className('btn btn-default')).click();
	   
	  var myAlertText;
	  browser.switchTo().alert().then(function (alert) {	//assertion
	          if (alert) {
	              alert.getText(function(alertText){
	                  expect(alertText).toContain('Customer added successfully ');
	                  myAlertText = alertText;
	              });
	              return alert.accept();
	          }
	      });
	  console.log('Pop message will appear & says Customer added sucessfully with its autogenerated customer id');

	   });
  xit('To oppen Account for doller', function() {
	   		
	   element(by.partialButtonText('Bank Manager Login')).click();
	   element(by.buttonText('Open Account')).click();
		 
	   $('#userSelect').$('[value="5"]').click();
	   $('#currency').$('[value="Dollar"]').click();
	   element(by.buttonText('Process')).click();
	   
	  browser.switchTo().alert().then(function (alert) {	//assertion
          if (alert) {
              alert.getText(function(alertText){
                  expect(alertText).toContain('Account created successfully with account Number');
              });
          }
      });
	   browser.sleep(3000);
		console.log('Pop message will appear with autogenerated account Number for doller');
	   });
  xit('To oppen Account for pound', function() {
	  		
	   element(by.partialButtonText('Bank Manager Login')).click();
	   element(by.buttonText('Open Account')).click();
		 
	   $('#userSelect').$('[value="5"]').click();
	   $('#currency').$('[value="Pound"]').click();
	   element(by.buttonText('Process')).click();
	   browser.sleep(3000);
	   
	  var alert; 
	  browser.switchTo().alert().then(function (alert) {	//assertion
        if (alert) {
            alert.getText(function(alertText){
                expect(alertText).toEqual('Account created successfully with account Number :1019');
            });
            return alert.accept();
        }
    });
	  
	   browser.sleep(3000);
		console.log('Pop message will appear with autogenerated account Number for pound');
	   });
  xit('To oppen Account for Rupee', function() {
		
	   element(by.partialButtonText('Bank Manager Login')).click();
	   element(by.buttonText('Open Account')).click();
		 
	   $('#userSelect').$('[value="5"]').click();
	   $('#currency').$('[value="Rupee"]').click();
	   element(by.buttonText('Process')).click();
	   browser.sleep(3000);
	   
	  var alert; 
	  browser.switchTo().alert().then(function (alert) {	//assertion
      if (alert) {
          alert.getText(function(alertText){
              expect(alertText).toEqual('Account created successfully with account Number :1020');
          });
          return alert.accept();
      }
	  });
	   browser.sleep(3000);
		console.log('Pop message will appear with autogenerated account Number for rupee');
	   });
  
  xit('To delete Customer', function() {
		
	   element(by.partialButtonText('Bank Manager Login')).click();
	   element(by.buttonText('Customers')).click();
	   element(by.model('searchCustomer')).sendKeys('Ron');
	   browser.sleep(3000);
	   element(by.partialButtonText('Delete')).click();
	   
	   browser.sleep(3000);
		console.log('customer is deleted');
	   });
  xit('For Customer Login', function() {
		
	   element(by.partialButtonText('Customer Login')).click();
	  
	   $('#userSelect').$('[value="2"]').click();
	   element(by.buttonText('Login')).click(); 
	   expect(element(by.partialLinkText('Welcome Harry Potter !!')));
	   
	   console.log('Harry potter login page is displayed');
	   });
  xit('verifyCurrencyType', function() {
		
	   element(by.partialButtonText('Customer Login')).click();
	  
	   $('#userSelect').$('[value="2"]').click();
	   element(by.buttonText('Login')).click(); 
	   expect(element(by.partialLinkText('Welcome Harry Potter !!')));
	   
	   console.log('Harry potter login page is displayed');
	  // $('#accountSelect').$('[value="number:1004"]').click();
	   $('#accountSelect').$('[label="1004"]').click();
	   var text=element(by.xpath('html/body/div[3]/div/div[2]/div/div[2]/strong[3]')).getText();
	   expect(text.getText()).toBe('Dollar');//assertion
	   browser.sleep(3000);
	   
	   $('#accountSelect').$('[label="1005"]').click();
	   var text1=element(by.xpath('html/body/div[3]/div/div[2]/div/div[2]/strong[3]')).getText();
	   expect(text1.getText()).toBe('Pound');//assertion
	   browser.sleep(3000);
	   
	   $('#accountSelect').$('[label="1006"]').click();
	   var text2=element(by.xpath('html/body/div[3]/div/div[2]/div/div[2]/strong[3]')).getText();
	   expect(text2.getText()).toBe('Rupee');//assertion
	   
	   });
  
  xit('InitialTraction', function() {
		
	   element(by.partialButtonText('Customer Login')).click();
	  
	   $('#userSelect').$('[value="2"]').click();
	   element(by.buttonText('Login')).click(); 
	   expect(element(by.partialLinkText('Welcome Harry Potter !!')));
	   
	   element(by.buttonText('Transactions')).click();
	   
	   element.all(by.repeater("tx in transactions").column('Amount.value')).getText().then(function(text) {
		   
			console.log('Total Amount ='+text);
	   console.log('Total amount is empty');
	   });
	   });

  it('InitialTraction', function() {
		
	   element(by.partialButtonText('Customer Login')).click();
	  
	   $('#userSelect').$('[value="2"]').click();
	   element(by.buttonText('Login')).click(); 
	   expect(element(by.partialLinkText('Welcome Harry Potter !!')));
	   console.log('Harry potter login page is displayed');
	   
	   $('#accountSelect').$('[label="1006"]').click();
	   element(by.partialButtonText('Deposit')).click();
	   element(by.model('amount')).sendKeys('2000');
	   browser.sleep(3000);
	   element(by.className('btn btn-default')).click();
	   
	   var balance=element(by.xpath('html/body/div[3]/div/div[2]/div/div[2]/strong[2]')).getText();
	   expect(balance.getText()).toBe('2000');
	   console.log('Balance is 2000 for the account number 1006');
	   });
  
  xit('TransationAfterDeposit', function() {//first enter the initial transaction then you can read the table
		
	   element(by.partialButtonText('Customer Login')).click();
	  
	   $('#userSelect').$('[value="2"]').click();
	   element(by.buttonText('Login')).click(); 
	   expect(element(by.partialLinkText('Welcome Harry Potter !!')));
	   console.log('Harry potter login page is displayed');
	   
	   $('#accountSelect').$('[label="1006"]').click();
	   element(by.partialButtonText('Transactions')).click();
	   browser.sleep(3000);
	   
	   element.all(by.repeater("tx in transactions")).then(function(text) {
		   	for(i=0;i<text.length;i++){
		   		text[i].getText().then(function(data) {	
		   			console.log(data);
		   		});
		   	};
		   });
	  // console.log('Amount : 2000 traction type : Credit')
});
  xit('withdrawl error', function() {
		
	   element(by.partialButtonText('Customer Login')).click();
	  
	   $('#userSelect').$('[value="2"]').click();
	   element(by.buttonText('Login')).click(); 
	   expect(element(by.partialLinkText('Welcome Harry Potter !!')));
	   console.log('Harry potter login page is displayed');
	   
	   $('#accountSelect').$('[label="1006"]').click();
	   element(by.partialButtonText('Withdrawl')).click();
	   browser.sleep(3000);
	   element(by.model('amount')).sendKeys('2001');
	   browser.sleep(3000);
	   element(by.className('btn btn-default')).click();
	   
	   var error= element(by.className('error ng-binding')).getText();   
	   expect(error.getText()).toBe('Transaction Failed. You can not withdraw amount more than the balance.');//assertion
	    
  });
 it('withdrawl success', function() {//first enter the initial transaction amount then perform this operation
		
	   element(by.partialButtonText('Customer Login')).click();//first Deposit then withdrawl
	  
	   $('#userSelect').$('[value="2"]').click();
	   element(by.buttonText('Login')).click(); 
	   expect(element(by.partialLinkText('Welcome Harry Potter !!')));
	   console.log('Harry potter login page is displayed');
	   
	   $('#accountSelect').$('[label="1006"]').click();
	   element(by.partialButtonText('Withdrawl')).click();
	   browser.sleep(3000);
	   element(by.model('amount')).sendKeys('1000');
	   browser.sleep(3000);
	   element(by.className('btn btn-default')).click();
	   
	   var msg= element(by.className('error ng-binding')).getText();   
	   expect(msg.getText()).toBe('Transaction successful');//assertion
	    
 });
  it('TransationAfterWithdrawl', function() {//first initial transaction then 1000 withdrawl then do this step
		
	   element(by.partialButtonText('Customer Login')).click();
	  
	   $('#userSelect').$('[value="2"]').click();
	   element(by.buttonText('Login')).click(); 
	   expect(element(by.partialLinkText('Welcome Harry Potter !!')));
	   console.log('Harry potter login page is displayed');
	   
	   $('#accountSelect').$('[label="1006"]').click();
	   element(by.partialButtonText('Transactions')).click();
	   browser.sleep(3000);
	
	   element.all(by.repeater("tx in transactions")).then(function(text) {
		   	for(i=0;i<text.length;i++){
		   		text[i].getText().then(function(data) {	
		   			console.log(data);
		   		});
		   	};
		   });
});
  xit('Transation Reset', function() {
		
	   element(by.partialButtonText('Customer Login')).click();
	  
	   $('#userSelect').$('[value="2"]').click();
	   element(by.buttonText('Login')).click(); 
	   expect(element(by.partialLinkText('Welcome Harry Potter !!')));
	   console.log('Harry potter login page is displayed');
	   
	   $('#accountSelect').$('[label="1006"]').click();
	   element(by.partialButtonText('Transactions')).click();
	   browser.sleep(3000);
	  
	   console.log('Transaction table is empty, cannot read the the table');
});
  xit('To go to main age', function() {
		
	   element(by.partialButtonText('Customer Login')).click();
	  
	   $('#userSelect').$('[value="2"]').click();
	   element(by.buttonText('Login')).click(); 
	   expect(element(by.partialLinkText('Welcome Harry Potter !!')));
	   console.log('Harry potter login page is displayed');
	   
	   $('#accountSelect').$('[label="1006"]').click();
	   element(by.partialButtonText('Transactions')).click();
	   browser.sleep(3000);
	   
	   element(by.partialButtonText('Back')).click();
	   var text= element(by.className('fontBig ng-binding')).getText();
	   expect(text.getText()).toEqual('Harry Potter');
	   console.log('Harry potter login page is opened');
});
  xit('To Logout', function() {
		
	   element(by.partialButtonText('Customer Login')).click();
	  
	   $('#userSelect').$('[value="2"]').click();
	   element(by.buttonText('Login')).click(); 
	   expect(element(by.partialLinkText('Welcome Harry Potter !!')));
	   console.log('Harry potter login page is displayed');
	   
	  element(by.buttonText('Logout')).click();
	  
	  titleGot = browser.getTitle().then(function(promisedResult){
	      console.log("Title is : " + promisedResult);
	      return promisedResult;

	  })
	  console.log("Title Got is " + titleGot);
	  
});
});
